# Dedicated Foot configuration for Cava under Waybar
# Isolated from global foot.ini for seamless transparent visualization

include=~/.cache/wal/colors-foot.ini

font=JetBrainsMono Nerd Font:size=5
pad=0x0 center

[cursor]
style=underline
blink=no

[colors-dark]
alpha=0.0
background=000000

[csd]
preferred=none

[bell]
urgent=no
notify=no
visual=no
